---
driver:
  name: dokken
  chef_version: latest

provisioner:
  name: dokken
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true
  chef_license: accept-no-persist

transport:
  name: dokken

verifier:
  name: inspec

platforms:
  - name: ubuntu-20.04
    driver:
      image: index.docker.io/dokken/ubuntu-20.04
  - name: ubuntu-21.04
    driver:
      image: index.docker.io/dokken/ubuntu-21.04

suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[universal-ctags::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:

  - name: params
    run_list:
      - recipe[apt]
      - role[params]
    verifier:
      inspec_tests:
        - test/integration/params
