---
driver:
  name: docker

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true
  chef_license: accept-no-persist

verifier:
  name: inspec

platforms:
  - name: ubuntu-20.04

suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[universal-ctags::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
