version: 2.1

orbs:
  ruby: circleci/ruby@1.1.2

jobs:
  build:
    machine:
      image: "ubuntu-2004:202010-01"
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install curl
      - ruby/install:
          version: "2.7.2"
      - checkout
      - run: bundle install
      - run: bundle exec kitchen test
