version: 2.1

jobs:
  build:
    machine:
      image: "ubuntu-2004:202104-01"
    steps:
      - run: source /opt/circleci/.rvm/scripts/rvm
      - run: export PATH=/opt/circleci/.rvm/bin:$PATH && rvm install 2.7.2
      - checkout
      - run: export PATH=/opt/circleci/.rvm/bin:$PATH && bundle install
      - run: export PATH=/opt/circleci/.rvm/bin:$PATH && bundle exec kitchen test
