version: 2.1

jobs:
  build:
    machine:
      image: "ubuntu-2004:202104-01"
    steps:
      - run: source /opt/circleci/.rvm/scripts/rvm
      - run: rvm install 3.0.1
      - checkout
      - run: bundle install
      - run: bundle exec kitchen test
