version: 2.1

jobs:
  build:
    machine:
      image: "ubuntu-2004:202104-01"
    steps:
      - run: source /opt/circleci/.rvm/scripts/rvm
      - run: rvm install 2.7.2
      - checkout
      - run: rvm local 2.7.2 && bundle install
      - run: bundle exec kitchen test
