version: 2.1

jobs:
  build:
    machine:
      image: "ubuntu-2004:202010-01"
    steps:
      - run: source /opt/circleci/.rvm/scripts/rvm
      # To fix libpaper install error
      - run: apt install locales-all
      - run: rvm install 2.7.2
      - checkout
      - run: bundle install
      - run: bundle exec kitchen test
